name: Release Storages

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org/
      - name: Setup Deno
        uses: denoland/setup-deno@v2
      - run: npm i -g pnpm
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run format:check
      - run: pnpm run build
      - run: pnpm run test
      - name: Create and Publish versions
        run: |
          pnpm publish --access public --no-git-checks -r
      - name: Publish to JSR
        run: |
          pnpm sync:jsr-versions
          for dir in packages/*/; do
            (cd "$dir" && pnpm dlx jsr publish) || exit 1
          done
